### ISSUE TITLE
Argument "" isn't numeric in addition (+)

### ISSUE THREAD

**Issue by flintforge** [jonathanio/monitoring-munin-haproxy#2]
```
munin-run haproxyng
```

and **_use warnings;_**

Argument "" isn't numeric in addition (+) at /etc/munin/plugins/haproxyng line 224, <GEN0> line 4.
Argument "" isn't numeric in addition (+) at /etc/munin/plugins/haproxyng line 224, <GEN0> line 4.
Argument "" isn't numeric in addition (+) at /etc/munin/plugins/haproxyng line 224, <GEN0> line 4.
Argument "" isn't numeric in addition (+) at /etc/munin/plugins/haproxyng line 224, <GEN0> line 4.
Argument "" isn't numeric in addition (+) at /etc/munin/plugins/haproxyng line 224, <GEN0> line 4.
Argument "" isn't numeric in addition (+) at /etc/munin/plugins/haproxyng line 224, <GEN0> line 4.
Argument "" isn't numeric in addition (+) at /etc/munin/plugins/haproxyng line 204, <GEN0> line 5.
Argument "" isn't numeric in addition (+) at /etc/munin/plugins/haproxyng line 204, <GEN0> line 5.
Argument "" isn't numeric in addition (+) at /etc/munin/plugins/haproxyng line 204, <GEN0> line 5.
Argument "" isn't numeric in addition (+) at /etc/munin/plugins/haproxyng line 204, <GEN0> line 5.
Argument "" isn't numeric in addition (+) at /etc/munin/plugins/haproxyng line 204, <GEN0> line 5.
Argument "" isn't numeric in addition (+) at /etc/munin/plugins/haproxyng line 204, <GEN0> line 5.
Argument "" isn't numeric in addition (+) at /etc/munin/plugins/haproxyng line 224, <GEN0> line 6.
Argument "" isn't numeric in addition (+) at /etc/munin/plugins/haproxyng line 224, <GEN0> line 6.
Argument "" isn't numeric in addition (+) at /etc/munin/plugins/haproxyng line 224, <GEN0> line 6.
Argument "" isn't numeric in addition (+) at /etc/munin/plugins/haproxyng line 224, <GEN0> line 6.
Argument "" isn't numeric in addition (+) at /etc/munin/plugins/haproxyng line 224, <GEN0> line 6.
Argument "" isn't numeric in addition (+) at /etc/munin/plugins/haproxyng line 224, <GEN0> line 6.
Argument "" isn't numeric in addition (+) at /etc/munin/plugins/haproxyng line 204, <GEN0> line 7.
Argument "" isn't numeric in addition (+) at /etc/munin/plugins/haproxyng line 204, <GEN0> line 7.
Argument "" isn't numeric in addition (+) at /etc/munin/plugins/haproxyng line 204, <GEN0> line 7.
Argument "" isn't numeric in addition (+) at /etc/munin/plugins/haproxyng line 204, <GEN0> line 7.
Argument "" isn't numeric in addition (+) at /etc/munin/plugins/haproxyng line 204, <GEN0> line 7.
Argument "" isn't numeric in addition (+) at /etc/munin/plugins/haproxyng line 204, <GEN0> line 7.

**Comment by marji** [comment]
I see something very similar - on ubuntu 15.10
perl 5.20.2-6ubuntu0.2
haproxy 1.6.3-1

Argument "" isn't numeric in addition (+) at /etc/munin/plugins/haproxyng line 224, <GEN0> line 3.
Argument "" isn't numeric in addition (+) at /etc/munin/plugins/haproxyng line 224, <GEN0> line 3.
Argument "" isn't numeric in addition (+) at /etc/munin/plugins/haproxyng line 224, <GEN0> line 3.
Argument "" isn't numeric in addition (+) at /etc/munin/plugins/haproxyng line 224, <GEN0> line 3.
Argument "" isn't numeric in addition (+) at /etc/munin/plugins/haproxyng line 224, <GEN0> line 3.
Argument "" isn't numeric in addition (+) at /etc/munin/plugins/haproxyng line 224, <GEN0> line 3.
Argument "" isn't numeric in addition (+) at /etc/munin/plugins/haproxyng line 204, <GEN0> line 4.
Argument "" isn't numeric in addition (+) at /etc/munin/plugins/haproxyng line 204, <GEN0> line 4.
Argument "" isn't numeric in addition (+) at /etc/munin/plugins/haproxyng line 204, <GEN0> line 4.
Argument "" isn't numeric in addition (+) at /etc/munin/plugins/haproxyng line 204, <GEN0> line 4.
Argument "" isn't numeric in addition (+) at /etc/munin/plugins/haproxyng line 204, <GEN0> line 4.
Argument "" isn't numeric in addition (+) at /etc/munin/plugins/haproxyng line 204, <GEN0> line 4.
Argument "" isn't numeric in addition (+) at /etc/munin/plugins/haproxyng line 224, <GEN0> line 6.
Argument "" isn't numeric in addition (+) at /etc/munin/plugins/haproxyng line 224, <GEN0> line 6.
Argument "" isn't numeric in addition (+) at /etc/munin/plugins/haproxyng line 224, <GEN0> line 6.
Argument "" isn't numeric in addition (+) at /etc/munin/plugins/haproxyng line 224, <GEN0> line 6.
Argument "" isn't numeric in addition (+) at /etc/munin/plugins/haproxyng line 224, <GEN0> line 6.
Argument "" isn't numeric in addition (+) at /etc/munin/plugins/haproxyng line 224, <GEN0> line 6.
Argument "" isn't numeric in addition (+) at /etc/munin/plugins/haproxyng line 204, <GEN0> line 7.
Argument "" isn't numeric in addition (+) at /etc/munin/plugins/haproxyng line 204, <GEN0> line 7.
Argument "" isn't numeric in addition (+) at /etc/munin/plugins/haproxyng line 204, <GEN0> line 7.
Argument "" isn't numeric in addition (+) at /etc/munin/plugins/haproxyng line 204, <GEN0> line 7.
Argument "" isn't numeric in addition (+) at /etc/munin/plugins/haproxyng line 204, <GEN0> line 7.
Argument "" isn't numeric in addition (+) at /etc/munin/plugins/haproxyng line 204, <GEN0> line 7.
Argument "" isn't numeric in addition (+) at /etc/munin/plugins/haproxyng line 224, <GEN0> line 9.
Argument "" isn't numeric in addition (+) at /etc/munin/plugins/haproxyng line 224, <GEN0> line 9.
Argument "" isn't numeric in addition (+) at /etc/munin/plugins/haproxyng line 224, <GEN0> line 9.
Argument "" isn't numeric in addition (+) at /etc/munin/plugins/haproxyng line 224, <GEN0> line 9.
Argument "" isn't numeric in addition (+) at /etc/munin/plugins/haproxyng line 224, <GEN0> line 9.
Argument "" isn't numeric in addition (+) at /etc/munin/plugins/haproxyng line 224, <GEN0> line 9.
Argument "" isn't numeric in addition (+) at /etc/munin/plugins/haproxyng line 204, <GEN0> line 10.
Argument "" isn't numeric in addition (+) at /etc/munin/plugins/haproxyng line 204, <GEN0> line 10.
Argument "" isn't numeric in addition (+) at /etc/munin/plugins/haproxyng line 204, <GEN0> line 10.
Argument "" isn't numeric in addition (+) at /etc/munin/plugins/haproxyng line 204, <GEN0> line 10.
Argument "" isn't numeric in addition (+) at /etc/munin/plugins/haproxyng line 204, <GEN0> line 10.
Argument "" isn't numeric in addition (+) at /etc/munin/plugins/haproxyng line 204, <GEN0> line 10.

**Comment by jonathanio** [comment]
I'll look into this on the weekend.

**Comment by jonathanio** [comment]
@flintforge, @marji,

Sorry for the delay. I've added some default overrides into `get_data` which should resolve this warning. Please feel free to check the version in PR #3 and let me know if this fixes your problem.
